### ISSUE TITLE
Question about building the MeshGrading Plugin

### ISSUE THREAD

**Issue by shengchiliu** [oweissbarth/OpenFlipper-MeshGrading#1]
It's not an issue, but a question that how to build this tool.
Do I need to compile MeshGrading with the whole OpenFlipper? Or there is another way to load the plugin directly in the OpenFlipper?

**Comment by oweissbarth** [comment]
I added some build instructions here:
https://github.com/oweissbarth/OpenFlipper-MeshGrading/blob/master/README.md
It should be possible to build it on its own as it compiles to a single shared object. However the OpenFlipper build process does not seem to be set up for that.
